djangoticket/urls.py
# The MIT License (MIT)
# Copyright (c) [2015] [Houtmann Hadrien]
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the Aidez-moi), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.site.site_header = 'Aidez-Moi Administration'  # Change le nom de l'administration

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'djangoticket.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       url(r'^admin/', include(admin.site.urls)),

                       url(r'^', include('ticket.urls')),

                       )

ticket/urls.py
# coding=utf-8
__author__ = 'had'

# The MIT License (MIT)
# Copyright (c) [2015] [Houtmann Hadrien]
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the Aidez-moi), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('ticket.views',

                       url(r'^$', 'home.home'),
                       url(r'^login/$', 'auth.user_login'),
                       url(r'^add_ticket/$', 'tickets.add_ticket'),
                       url(r'^ticket_list_new/$', 'tickets.ticket_list_new'),
                       url(r'^ticket_list_clos/$', 'tickets.ticket_list_clos'),
                       url(r'^ticket_list_work/$', 'tickets.ticket_list_work'),
                       url(r'^ticket_list_incomplete/$', 'tickets.ticket_list_incomplet'),
                       url(r'^ticket_list_resolved/$', 'tickets.ticket_list_resolved'),
                       url(r'^ticket/edit_id=(?P<id>\d+)$', 'tickets.ticket_edit'),
                       url(r'^ticket/id=(?P<id>\d+)$', 'tickets.view_ticket', name='view'),
                       url(r'^ticket_all/$', 'tickets.ticket_all'),
                       url(r'^my_ticket_assign/$', 'tickets.my_ticket_assign'),
                       url(r'^delete/id=(?P<id>\d+)$', 'tickets.delete_ticket'),
                       url(r'^set_incomplete/id=(?P<id>\d+)$', 'tickets.set_incomplete'),
                       url(r'^set_complete/id=(?P<id>\d+)$', 'tickets.set_complete'),
                       url(r'^statistiques/$', 'stats.statistic'),
                       url(r'^ticket_stats/id=(?P<id>\d+)$', 'stats.ticket_stats'),
                       url(r'^logout/$', 'auth.logout_view'),
                       url(r'^configuration/$', 'configuration.view_configuration'),
                       url(r'^ticket_last_24/$', 'tickets.ticket_last_24'),
                       url(r'^ticket_last_month/$', 'tickets.ticket_last_month'),

                       ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket/models.py
# coding=utf-8

# The MIT License (MIT)
# Copyright (c) [2015] [Houtmann Hadrien]
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the Aidez-moi), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.utils.translation import ugettext as _
from django.contrib.auth.models import AbstractBaseUser


# import reversion



class Entity(models.Model):
    """
    Modele pour créer des entités, exemple service comptabilité
    """
    name = models.TextField(
        verbose_name=_('Nom'))

    description = models.TextField(
        verbose_name=_('Description'),
        null=True,
        blank=True)

    telephone = models.TextField(
        verbose_name=_('Téléphone'),
        null=True,
        blank=True)

    adress = models.TextField(
        verbose_name=_('Adresse'),
        null=True,
        blank=True)

    postal = models.TextField(
        verbose_name=_('Code postal'),
        null=True,
        blank=True)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


class Tickets(models.Model):

    title = models.TextField(
        verbose_name=_('Titre'),
        max_length=150,
        db_index=True)

    content = models.TextField(
        verbose_name=_('Contenu'), max_length=500)

    create_by = models.ForeignKey(
        User,
        verbose_name=_('Crée par'), db_index=True )

    created = models.DateTimeField(
        verbose_name=_('Crée le'), )

    last_edited = models.DateTimeField(
        verbose_name=_('Edité le'),
        auto_now=True, db_index=True)

    category = models.ForeignKey(
        'TicketCategory',
        verbose_name=_('Catégorie'),
        null=True,
        blank=True, db_index=True)

    # Marque le ticket comme incomplete et attente d'informations
    complete = models.BooleanField(
        default=1,
        verbose_name=_('Complet'))

    depends_on = models.CharField(
        null=True,
        blank=True,
        verbose_name=_('Dépend'),
        max_length=100, db_index=True)

    file = models.FileField(
        null=True,
        blank=True,
        upload_to='media',
        verbose_name=_('Fichier'))

    date_closed = models.DateTimeField(
        verbose_name=_('Date de cloture le'),
        blank=True,
        null=True)

    date_assigned = models.DateTimeField(
        verbose_name=_('Assigné le'),
        blank=True,
        null=True, db_index=True)

    date_resolved = models.DateTimeField(
        verbose_name=_('Résolution le'),
        blank=True,
        null=True, db_index=True)

    ask_to_delete = models.BooleanField(
        default=0,
        verbose_name=_('Marquer pour suppression'))

    entity = models.ForeignKey(
        'Entity',
        verbose_name=_('Entité'),
        blank=True,
        null=True, db_index=True)

    TYPES_CHOICES = (
        ('INCIDENT', _('Incident')),
        ('ASK', _('Demande')),)

    types = models.CharField(
        max_length=15,
        verbose_name=_('Types'),
        choices=TYPES_CHOICES)

    OPEN_STATUS = 'OPEN'

    STATUS_CHOICES = (
        ('OPEN', _('Ouvert')),
        ('RESOLVED', _('Résolus')),
        ('CLOSED', _('Clos')),
    )

    PRIORITY_CHOICES = (
        ('CRITICAL', _('Critique')),
        ('HIGH', _('Haute')),
        ('NORMAL', _('Normal')),
        ('LOW', _('Basse')),
        ('VERYLOW', _('Très basse')),)

    assign_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='assigned_to',
        blank=True,
        null=True,
        verbose_name=(_('Assigné à')), db_index=True
    )

    status = models.CharField(
        max_length=15,
        choices=STATUS_CHOICES,
        default=OPEN_STATUS,
        verbose_name=_('Statut'), db_index=True )

    priority = models.CharField(
        max_length=15,
        choices=PRIORITY_CHOICES,
        default='NORMAL',
        blank='NORMAL',
        help_text=_(
        '1 = Highest Priority, 5 = Low Priority'),
        verbose_name=_('Priorité'), db_index=True )

    def __str__(self):
        """
        Cette méthode que nous définirons dans tous les modèles
        nous permettra de reconnaître facilement les différents objets que
        nous traiterons plus tard et dans l'administration
        """
        return self.title


#reversion.register(Tickets)


class TicketCategory(models.Model):
    """
    Nom de catégorie pour mieux cibler les tickets
    """
    category = models.TextField(verbose_name=_('Catégorie'), max_length=500)

    def __str__(self):
        """
        Cette méthode que nous définirons dans tous les modèles
        nous permettra de reconnaître facilement les différents objets que
        nous traiterons plus tard et dans l'administration
        """
        return self.category


class Follow(models.Model):
    """
    Pour suivre les changements et les reponse d'un ticket
    """

    follow_by = models.ForeignKey(
        User,
        related_name='follower')

    follow = models.TextField(
        blank=True,
        null=True)

    ticket = models.ForeignKey(
        Tickets,
        related_name='ticket_id')

    date_follow = models.DateTimeField(
        auto_now=True, )

    old_value = models.TextField(
        blank=True,
        null=True)

    new_value = models.TextField(
        blank=True,
        null=True)



class UserProfile(models.Model):
    user = models.OneToOneField(User)
    ticket_per_page = models.IntegerField(
                        default=25,
                        verbose_name=_('Nombre de ticket par page'))
    active_mail = models.BooleanField(
                        default=0,
        verbose_name=_('Notification par mail')
                                      )

ticket/views/configuration.py
# coding=utf-8

# The MIT License (MIT)
# Copyright (c) [2015] [Houtmann Hadrien]
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the Aidez-moi), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


from django.shortcuts import render, redirect, get_object_or_404
from ticket.views.home import home
from ticket.forms.configuration_forms import ConfigForm
from ticket.models import User, UserProfile
from django.views.decorators.cache import cache_page

@cache_page(60 * 5)
def view_configuration(request):
    """
    :param request:
    :return: La page qui sert de configuration pour les profiles utilisateurs
    """

    try:
        user = UserProfile.objects.get(user=request.user)
        config_form = ConfigForm(instance=user)

    except UserProfile.DoesNotExist:
        UserProfile.objects.create(user=request.user,
                                   active_mail=1,
                                   ticket_per_page=25)
        user = UserProfile.objects.get(user=request.user)


    if request.method == 'POST':

        config_form = ConfigForm(request.POST, instance=user)
        if config_form.is_valid():
            config = config_form.save()

            # met le cookies 'perpage' à jour avec la valeur ticket_per_page
            request.session['perpage'] = config.ticket_per_page
    else:
        config_form = ConfigForm(instance=user)

    return render(request, 'configuration.html', locals())

ticket/views/files.py
# coding=utf-8
__author__ = 'had'

# The MIT License (MIT)
# Copyright (c) [2015] [Houtmann Hadrien]
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the Aidez-moi), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from ticket.models import Tickets, UserProfile, Follow
from ticket.views.auth import home

from django.http import HttpResponse


@login_required(login_url='login/')
def telecharger_fichier(request, id):
    # Faire un truc ici qui génère le fichier
    # ou qui récupère un fichier existant.
    # l'important est d'avoir le chemin ABSOLU du fichier
    chemin_vers_fichier = Tickets.objects.get(id).filter('file')

    # On crée la réponse à la main
    response = HttpResponse()

    # On laisse nginx s'occuper de détecter le mimetype
    del response['content-type']
    # On met un header que nginx va comprendre comme "sert le fichier à ma place"
    response['X-Accel-Redirect'] = chemin_vers_fichier
    return response

ticket/views/tickets_tri.py
# coding=utf-8
__author__ = 'had'

# The MIT License (MIT)
# Copyright (c) [2015] [Houtmann Hadrien]
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the Aidez-moi), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


from datetime import datetime
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django_tables2 import RequestConfig
from ticket.forms.forms import TicketForm, ResponseForm, StatusForm
from ticket.models import Tickets, UserProfile, Follow, Entity
from ticket.views.home import home
from ticket.tables import TicketsTables
from django.contrib import messages
from django.utils.translation import ugettext as _
from ticket.tasks import send_new_ticket_all_staff, incomplete_ticket
from djangoticket.settings import USE_MAIL
import json

ticket/templates/add_ticket.html
{% extends "base.html" %}

{% load i18n %}
{% block content %}

    <div class="ui two column centered grid">
    <div class="column">

<fieldset>
    <form enctype="multipart/form-data" class="ui form"  method="POST">{% csrf_token %}



<div class="uk-form">

    <table class="ui table">

    <div class="">
       {{ form.title }}
        <div class="ui divider"></div>
    </div>

        <div class="">
       {{ form.content }}
        <div class="ui divider"></div>
    </div>
      <tbody>
        <tr>
          <td>{{ form.assign_to.label }}<p></p>{{ form.assign_to }}</td>
          <td>{{ form.priority.label }}<p></p>{{ form.priority }}</td>
        </tr>

        <tr>
          <td>{{ form.category.label }}<p></p>{{ form.category }}</td>
          <td>{{ form.types.label }}<p></p>{{ form.types }}</td>
        </tr>

        <tr>
          <td>{{ form.depends_on.label }}<p></p>{{ form.depends_on }}</td>
          <td>{{ form.status.label }}<p></p>{{ form.status }}</td>
        </tr>
        <tr>
          <td>{{ form.entity.label }}<p></p>{{ form.entity }}</td>
          <td>{% trans "Attacher un fichier" %}<p></p>{{ form.file}}</td>
        </tr>

    </table>

    <p></p></form>

    <center>
    <button class="ui submit button">{% trans "Soumettre" %}</button> </center></div>


</div>
</body>
{% endblock %}

ticket/templates/configuration.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="ui two column centered grid">
        <div class="column">
    <form  class="ui form"  method="POST">{% csrf_token %}



<div class="uk-form">
    <fieldset>
        {% for item in config_form %}
            {{ item.label }} : <p></p>{{ item }}<p></p>
        {% endfor %}
        <button class="ui submit button">{% trans "Sauvegarder" %}</button>
    </form>


{% endblock %}

ticket/templates/login.html
{% load i18n %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" /><title> Tickets </title>
<link rel="stylesheet" href="{{ STATIC_URL }}semantic.min.css" type="text/css" media="all" />

    </head>
<div class="ui two column centered grid">
    <div class="column">

                <h3 class="">Ticket</h3>
                <form class="ui form" action='' method="POST">{% csrf_token %}
                    <div class="ui form row">
                        {{ form.username }}
                    </div><p></p>
                    <div class="ui form row">
                        {{ form.password }}
                    </div>
                    <p></p>
                    <center><div class="ui form row ">
                        <button class="ui button ">Login</button>
                    </div></center>
                </form>
 </div>
</div>

ticket/templates/statistics.html
{% extends "base.html" %}

{% block content %}


{% endblock %}

ticket/templates/ticket.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    {% load filter %}

    <div class="ui two column centered grid">
        <div class="column">
            <fieldset>

                {% if messages %}
                    <div class="ui negative message">
                        <i class="close icon"></i>
                        {% for message in messages %}
                            <div{% if message.tags %} class="header {{ message.tags }}"{% endif %}>{{ message }}</div>
                        {% endfor %}
                    </div>
                {% endif %}

                <center>
                    <div class="ui  button"><a href="{% url "ticket.views.tickets.ticket_edit" tickets.id %}">
                        {% trans "Editer le ticket" %}</a></div>

                    <div class="ui  button"><a href="{% url "ticket.views.stats.ticket_stats" tickets.id %}">
                        {% trans "Statistiques" %}</a></div>

                    {% if request.user.is_staff %}
                        <div class="ui  button"><a href="{% url "ticket.views.tickets.delete_ticket" tickets.id %}">
                            {% trans "Supprimez le ticket" %}</a></div>



                        {% if tickets.complete == 0 %}
                            <div class="ui  button"><a href="{% url "ticket.views.tickets.set_complete" tickets.id %}">
                                {% trans "Marquer comme complet" %}</a></div>
                        {% else %}
                            <div class="ui  button"><a
                                    href="{% url "ticket.views.tickets.set_incomplete" tickets.id %}">
                                {% trans "Marquer comme incomplet" %}</a></div>
                        {% endif %}
                    {% else %}
                        <a class="uk-button" href="{% url "ticket.views.tickets.delete_ticket" tickets.id %}"
                           onclick="return confirm('Etes vous sure de vouloir supprimez ce ticket ?');">
                            {% trans "Demande de suppression" %}</a>

                    {% endif %}</center>


                <div class="ui message">
                    <div class="header">
                        {% trans "Titre" %} :
                    </div>
                    <p style="width: 40em; word-wrap: break-word;">{{ tickets.title }}</p>
                </div>

                <table class="ui table">
                    <thead>
                    <tr>
                        <th></th>
                        <th></th>

                    </tr>
                    </thead>
                    <tbody>

                    <tr>
                        <td>
                            <span class="uk-badge">Ticket id :# {{ tickets.id }}
                            </span>
                        </td>
                        <td> {% trans "Catégorie" %}:
                            {% if tickets.category == None %} {% trans "Pas de catégories" %}
                                {% else %}{{ tickets.category }}
                            {% endif %}
                        </td>
                    </tr>

                    <tr>


                    {% if tickets.priority  == 'CRITICAL' %}
                            <td> {% trans "Priorité" %} : <font color="FF3333">{{ tickets.get_priority_display | upper }}</font>
                        {% elif tickets.priority == 'HIGH' %}
                            <td>{% trans "Priorité" %} : <font color="FF8585">{{ tickets.get_priority_display | upper }}</font>
                        {% elif tickets.priority == 'NORMAL' %}
                            <td>{% trans "Priorité" %} : <font>{{ tickets.get_priority_display | upper }}</font>
                        {% elif tickets.priority == 'LOW' %}
                            <td>{% trans "Priorité" %} : <font color="FFC299">{{ tickets.get_priority_display | upper }}</font>
                        {% elif tickets.priority == 'VERYLOW' %}
                            <td>{% trans "Priorité" %} : <font color="FFE2CE">{{ tickets.get_priority_display | upper }}</font>

                            {% endif %}
                    </td>

                        <td>{% trans "Status" %} :

                            {% if tickets.status  == 'OPEN' %}
                            <div class="ui center orange label">{{ tickets.get_status_display }}</div>
                            {% elif tickets.status  == 'RESOLVED' %}
                            <div class="ui center green label">{{ tickets.get_status_display }}</div>
                            {% elif tickets.status  == 'CLOSED' %}
                            <div class="ui center black label">{{ tickets.get_status_display }}</div>
                            {% endif %}

                        </td>

                    </tr>
                    <tr>
                        <td>{% trans "Demandeur" %} : {{ tickets.create_by }}</td>
                        <td>{% trans "Type" %} : {{ tickets.get_types_display }}</td>

                    </tr>
                    <tr>
                        <td>{% trans "Crée le" %} : {{ tickets.created }}</td>
                        <td>{% if tickets.assign_to == None %}
                            {% trans "Assigné à" %} :
                            <span class="uk-text-warning">{% trans "Pas encore assigné" %}</span>
                        {% else %}
                            {% trans "Assigné à" %} : {{ tickets.assign_to }}
                        {% endif %}</td>
                    <tr>
                        <td>
                            {% trans "Derniere edition le" %} : {{ tickets.last_edited }}
                        </td>
                        <td>
                            {% if tickets.depends_on %}
                            {% trans "Depend" %}:
                            <a href=" {% url "ticket.views.tickets.view_ticket" tickets.depends_on %}">
                                {{ tickets.depends_on }}
                            </a></td> {% endif %}

                    </tr>
                    <tr><td>{% trans "Entité" %}: {{ tickets.entity }}</td></tr>

                    </tbody>
                </table>


                <div class="ui message">
                    <div class="header">
                        {% trans "Fichier :" %}
                    </div>
                    <p style=""><a href="/media/{{ tickets.file }}">{{ tickets.file }}</a></p>
                </div>

                <div class="ui message">
                    <div class="header">
                        {% trans "Ticket" %} :
                    </div>
                    <p style="width: 40em; word-wrap: break-word;">{{ tickets.content }}</p>
                </div>
        </div>

        <div class="ui  column centered grid">
            <div class="column">

                {% for item in follow_up %}
                    {% if item.follow == None %}
                        <div class="ui comments">
                        <div class="comment">

                            <div class="content">
                                <a class="author">{{ item.follow_by }}</a>

                                <div class="metadata">
                                    <span class="date">{{ item.date_follow }}</span>
                                </div>

                                <div class="text">
                                    {% compare item.old_value item.new_value as follows %}
                                    {% for follow in follows %}{{ follow }}<p></p>{% endfor %}<p></p>
                                </div>
                            </div>
                        </div>
                        <h3 class="ui dividing header"></h3>
                    {% else %}
                        <div class="ui comments">
                        <div class="comment">
                            <div class="content">
                                <a class="author">{{ item.follow_by }}</a>

                                <div class="metadata">
                                    <span class="date">{{ item.date_follow }}</span>
                                </div>
                                <div class="text">
                                    {{ item.follow }}
                                </div>
                            </div>
                        </div><h3 class="ui dividing header"></h3>
                    {% endif %}
                {% endfor %}


                <div class="comment"></div>
                <form class="ui form" action="" name="post_response" method="post">{% csrf_token %}

                    {% if messages %}
                        <ul class="ui warning message">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    {{ ticket_form.status }}<p></p>
                    {{ form.follow }}<p></p>

                    <center>
                        <button class="ui submit button">{% trans "Soumettre" %}</button>
                    </center>
                </form>

                </body>
{% endblock %}

ticket/templates/ticket_list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

    <div class="uk-container uk-container-center">


    </ul>
</nav>
{% load render_table from django_tables2 %}

        <link rel="stylesheet" href="{{ STATIC_URL }}paleblue/screen.css" />

    <body>
        {% render_table ticket_list %}
    </body>
    </div>


{% endblock %}

ticket/templates/ticket_stats.html
{% extends "base.html" %}

{% block content %}
<div class="ui two column centered grid">
    <div class="column">
<fieldset>

{% endblock %}